Repository fabricadesoftwareufs/MonitoraSUS, pull requests merged in 2020-04, with the labels that each got.

#12 PR - Issue02
  Codigo/Model/ViewModel/SecretarioMunicipioEstadoViewModel.cs
  Codigo/MonitoraSUS/Controllers/AgenteSecretarioController.cs
  Codigo/MonitoraSUS/Controllers/HomeController.cs
  Codigo/MonitoraSUS/Models/ErrorViewModel.cs
  Codigo/MonitoraSUS/MonitoraSUS.csproj
  Codigo/MonitoraSUS/Startup.cs
  Codigo/MonitoraSUS/Utils/Methods.cs
  Codigo/MonitoraSUS/Views/AgenteSecretario/Create.cshtml
  Codigo/MonitoraSUS/Views/AgenteSecretario/Index.cshtml
  Codigo/MonitoraSUS/Views/Home/Index.cshtml
  Codigo/MonitoraSUS/Views/Shared/_ValidationScriptsPartial.cshtml
  Codigo/MonitoraSUS/Views/_ViewImports.cshtml
  Codigo/Service/EstadoService.cs
  Codigo/Service/Interface/IMunicipioService.cs
  Codigo/Service/Interface/IPessoaService.cs
  Codigo/Service/Interface/IPessoaTrabalhaEstadoService.cs
  Codigo/Service/Interface/IPessoaTrabalhaMunicipioService.cs
  Codigo/Service/MunicipioService.cs
  Codigo/Service/PessoaService.cs
  Codigo/Service/PessoaTrabalhaEstadoService.cs
  Codigo/Service/PessoaTrabalhaMunicipioService.cs
Labels: enhancement

#18 PR - Issue17
  Codigo/Persistence/Empresaexame.cs
  Codigo/Persistence/Exame.cs
  Codigo/Persistence/Pessoatrabalhaestado.cs
  Codigo/Persistence/monitorasusContext.cs
  Documentacao/MonitoraSUS.mwb
  Documentacao/MonitoraSUS.mwb.bak
  Documentacao/scriptBD.sql
Labels: Correction

#20 PR - ISSUE14
  Codigo/MonitoraSUS/Controllers/LoginController.cs
  Codigo/MonitoraSUS/Views/AgenteSecretario/Create.cshtml
  Codigo/MonitoraSUS/Views/AgenteSecretario/Index.cshtml
  Codigo/MonitoraSUS/Views/Home/Index.cshtml
  Codigo/MonitoraSUS/Views/Shared/_Layout.cshtml
  Codigo/MonitoraSUS/Views/Shared/_NavBarPartial.cshtml
  Documentacao/MonitoraSUS.mwb
  Documentacao/MonitoraSUS.mwb.bak
Labels: Aprimoramento

#26 PR - Issue21
  Codigo/Model/EmailModel.cs
  Codigo/Model/EmpresaExameModel.cs
  Codigo/Model/EstadoModel.cs
  Codigo/Model/MunicipioModel.cs
  Codigo/Model/PessoaModel.cs
  Codigo/Model/PessoaTrabalhaEstadoModel.cs
  Codigo/Model/PessoaTrabalhaMunicipioModel.cs
  Codigo/Model/RecuperarSenhaModel.cs
  Codigo/Model/SituacaoPessoaVirusBacteriaModel.cs
  Codigo/Model/UsuarioModel.cs
  Codigo/Model/ViewModel/ExameViewModel.cs
  Codigo/Model/ViewModel/SecretarioMunicipioEstadoViewModel.cs
  Codigo/Model/ViewModel/UsuarioViewModel.cs
  Codigo/Model/VirusBacteriaModel.cs
  Codigo/MonitoraSUS/Controllers/AgenteSecretarioController.cs
  Codigo/MonitoraSUS/Controllers/ExameController.cs
  Codigo/MonitoraSUS/Controllers/LoginController.cs
  Codigo/MonitoraSUS/MonitoraSUS.csproj
  Codigo/MonitoraSUS/Program.cs
  Codigo/MonitoraSUS/Startup.cs
  Codigo/MonitoraSUS/Utils/Criptografia.cs
  Codigo/MonitoraSUS/Utils/Methods.cs
  Codigo/MonitoraSUS/Views/Home/Index.cshtml
  Codigo/MonitoraSUS/Views/Login/Index.cshtml
  Codigo/MonitoraSUS/Views/Login/RecuperarSenha.cshtml
  Codigo/MonitoraSUS/Views/Shared/_Layout.cshtml
  Codigo/MonitoraSUS/appsettings.json
  Codigo/Persistence/Empresaexame.cs
  Codigo/Persistence/Estado.cs
  Codigo/Persistence/Exame.cs
  Codigo/Persistence/Municipio.cs
  Codigo/Persistence/Pessoatrabalhaestado.cs
  Codigo/Persistence/Pessoatrabalhamunicipio.cs
  Codigo/Persistence/Recuperarsenha.cs
  Codigo/Persistence/Situacaopessoavirusbacteria.cs
  Codigo/Persistence/Usuario.cs
  Codigo/Persistence/Virusbacteria.cs
  Codigo/Persistence/monitorasusContext.cs
  Codigo/Service/EmailService.cs
  Codigo/Service/EmpresaExameService.cs
  Codigo/Service/EstadoService.cs
  Codigo/Service/ExameService.cs
  Codigo/Service/Interface/IEmailService.cs
  Codigo/Service/Interface/IEmpresaExameService.cs
  Codigo/Service/Interface/IPessoaTrabalhaEstadoService.cs
  Codigo/Service/Interface/IRecuperarSenhaService.cs
  Codigo/Service/Interface/ISituacaoVirusBacteriaService.cs
  Codigo/Service/Interface/IUsuarioService.cs
  Codigo/Service/MunicipioService.cs
  Codigo/Service/PessoaService .cs
  Codigo/Service/PessoaTrabalhaEstadoService.cs
  Codigo/Service/PessoaTrabalhaMunicipioService.cs
  Codigo/Service/RecuperarSenhaService.cs
  Codigo/Service/SituacaoVirusBacteriaService.cs
  Codigo/Service/UsuarioService.cs
  Codigo/Service/VirusBacteriaService.cs
  Documentacao/MonitoraSUS.mwb
  Documentacao/MonitoraSUS.mwb.bak
Labels: Correção, Nova Feature

#27 Branch excluir exame
  Codigo/Model/bin/Debug/netcoreapp2.1/Model.dll
  Codigo/Model/bin/Debug/netcoreapp2.1/Model.pdb
  Codigo/Model/obj/Debug/netcoreapp2.1/Model.dll
  Codigo/Model/obj/Debug/netcoreapp2.1/Model.pdb
  Codigo/MonitoraSUS/Controllers/ExameController.cs
  Codigo/MonitoraSUS/Utils/Methods.cs
  Codigo/MonitoraSUS/Views/Exame/Create.cshtml
  Codigo/MonitoraSUS/Views/Exame/Edit.cshtml
  Codigo/MonitoraSUS/Views/Exame/Index.cshtml
  Codigo/MonitoraSUS/Views/Shared/_Layout.cshtml
  Codigo/Service/Interface/ISituacaoVirusBacteriaService.cs
  Codigo/Service/SituacaoVirusBacteriaService.cs
  Codigo/Service/bin/Debug/netcoreapp2.1/Model.dll
  Codigo/Service/bin/Debug/netcoreapp2.1/Model.pdb
  Codigo/Service/bin/Debug/netcoreapp2.1/Service.dll
  Codigo/Service/bin/Debug/netcoreapp2.1/Service.pdb
  Codigo/Service/obj/Debug/netcoreapp2.1/Service.csprojAssemblyReference.cache
  Codigo/Service/obj/Debug/netcoreapp2.1/Service.dll
  Codigo/Service/obj/Debug/netcoreapp2.1/Service.pdb
  Documentacao/MonitoraSUS.mwb
  Documentacao/MonitoraSUS.mwb.bak
Labels: Correção, Nova Feature

#29 PR - Issue28
  Codigo/Model/PessoaModel.cs
  Codigo/Model/ViewModel/ExameViewModel.cs
  Codigo/MonitoraSUS/Controllers/AgenteSecretarioController.cs
  Codigo/MonitoraSUS/Controllers/ExameController.cs
  Codigo/MonitoraSUS/Controllers/LoginController.cs
  Codigo/MonitoraSUS/Utils/Methods.cs
  Codigo/MonitoraSUS/Views/AgenteSecretario/Create.cshtml
  Codigo/MonitoraSUS/Views/Login/Index.cshtml
  Codigo/MonitoraSUS/Views/Shared/_Layout.cshtml
  Codigo/MonitoraSUS/Views/Shared/_NavBarPartial.cshtml
  Codigo/MonitoraSUS/appsettings.json
  Codigo/Persistence/Pessoa.cs
  Codigo/Persistence/monitorasusContext.cs
  Codigo/Service/EmailService.cs
  Codigo/Service/Interface/IRecuperarSenhaService.cs
  Codigo/Service/RecuperarSenhaService.cs
  Documentacao/scriptBD.sql
Labels: Correção

#37 PR - Issue30
  Codigo/Model/ViewModel/AgenteMunicipioEstadoViewModel.cs
  Codigo/Model/ViewModel/SolicitanteAprovacaoModelView.cs
  Codigo/MonitoraSUS/Controllers/AgenteSecretarioController.cs
  Codigo/MonitoraSUS/Controllers/ExameController.cs
  Codigo/MonitoraSUS/Controllers/LoginController.cs
  Codigo/MonitoraSUS/Utils/Methods.cs
  Codigo/Service/PessoaTrabalhaMunicipioService.cs
  Codigo/Service/RecuperarSenhaService.cs
Labels: Correção

#39 PR - ISSUE38
  Codigo/MonitoraSUS/Controllers/AgenteSecretarioController.cs
  Codigo/MonitoraSUS/Views/AgenteSecretario/Create.cshtml
Labels: Correção, Nova Feature

#52 PR - Issue40
  Codigo/MonitoraSUS/Controllers/LoginController.cs
  Codigo/MonitoraSUS/Views/AgenteSecretario/Create.cshtml
  Codigo/MonitoraSUS/wwwroot/assets/js/PersonalScripts.js
Labels: Correção, Nova Feature

#53 PR - ISSUE40
  Codigo/MonitoraSUS/wwwroot/assets/js/PersonalScripts.js
Labels: Correção

#55 PR - ISSUE54
  Codigo/MonitoraSUS/Controllers/LoginController.cs
Labels: Correção

#56 Criar usuario actv 51
  Codigo/MonitoraSUS/Controllers/AgenteSecretarioController.cs
  Codigo/MonitoraSUS/Controllers/LoginController.cs
  Codigo/MonitoraSUS/Utils/Methods.cs
  Codigo/Service/Interface/IPessoaTrabalhaEstadoService.cs
  Codigo/Service/Interface/IPessoaTrabalhaMunicipioService.cs
  Codigo/Service/PessoaTrabalhaEstadoService.cs
  Codigo/Service/PessoaTrabalhaMunicipioService.cs
  Codigo/Service/UsuarioService.cs
Labels: Correção

#59 PR - ISSUE58
  Codigo/Model/PessoaModel.cs
  Codigo/MonitoraSUS/Controllers/AgenteSecretarioController.cs
  Codigo/MonitoraSUS/Controllers/ExameController.cs
  Codigo/MonitoraSUS/Utils/Methods.cs
  Codigo/MonitoraSUS/Views/AgenteSecretario/Create.cshtml
  Codigo/Persistence/Pessoa.cs
  Codigo/Persistence/monitorasusContext.cs
  Codigo/Service/PessoaService .cs
  Documentacao/scaffold-persistence.txt
  Documentacao/scriptBD.sql
Labels: Correção, Nova Feature

#61 Fix #50, Fix #49 e Fix #62
  Codigo/MonitoraSUS/Controllers/AgenteSecretarioController.cs
  Codigo/MonitoraSUS/Controllers/ErrosController.cs
  Codigo/MonitoraSUS/Controllers/ExameController.cs
  Codigo/MonitoraSUS/Views/AgenteSecretario/Create.cshtml
  Codigo/MonitoraSUS/Views/Exame/Create.cshtml
  Codigo/MonitoraSUS/Views/Exame/Edit.cshtml
  Codigo/MonitoraSUS/wwwroot/assets/js/PersonalScripts.js
  Codigo/MonitoraSUS/wwwroot/assets/js/resultado-exame.js
  Codigo/Service/ExameService.cs
  Codigo/Service/Interface/IExameService.cs
Labels: Correção, Nova Feature

#74 PR - ISSUE73
  Codigo/Model/EmpresaExameModel.cs
  Codigo/Model/PessoaModel.cs
  Codigo/Model/PessoaTrabalhaEstadoModel.cs
  Codigo/Model/VirusBacteriaModel.cs
  Codigo/MonitoraSUS/Controllers/AgenteSecretarioController.cs
  Codigo/MonitoraSUS/Controllers/EmpresaExameController.cs
  Codigo/MonitoraSUS/appsettings.json
  Codigo/Persistence/Empresaexame.cs
  Codigo/Persistence/Pessoatrabalhaestado.cs
  Codigo/Persistence/Virusbacteria.cs
  Codigo/Persistence/monitorasusContext.cs
  Codigo/Service/EmpresaExameService.cs
  Codigo/Service/EstadoService.cs
  Codigo/Service/Interface/IEstadoService.cs
  Codigo/Service/VirusBacteriaService.cs
  Documentacao/monitoraSUS-dump.sql
Labels: Correção, Nova Feature

#80 Ajustes layout
  Codigo/MonitoraSUS/Views/Login/Index.cshtml
  Codigo/MonitoraSUS/Views/Shared/_Layout.cshtml
  Codigo/MonitoraSUS/Views/Shared/_NavBarPartial.cshtml
  Codigo/MonitoraSUS/wwwroot/assets/css/login.css
  Codigo/MonitoraSUS/wwwroot/assets/img/logo-knuth.png
  Codigo/MonitoraSUS/wwwroot/assets/img/logo-sus-white.png
  Codigo/MonitoraSUS/wwwroot/assets/img/logo-ufs.png
Labels: Correção, Nova Feature
